<!-- OPEN KIOSK -->
<script type="application/javascript" src="chrome://securebrowser/content/js/sbdebug.js" />
<script type="application/javascript" src="chrome://jslib/content/jslib.js" />
<script type="application/javascript" src="chrome://securebrowser/content/js/utils.js" />
<script type="application/javascript" src="chrome://securebrowser/content/js/opensecurebrowser.js" />
<script type="application/javascript" src="chrome://securebrowser/content/js/securebrowser.js" />
